In [1]:
import numpy as np

In [6]:
#create matrix of n x m 
# default m = 1
n = 5
vec = np.random.rand(n)

matrix = np.random.rand(n, n)

In [7]:
print(vec)

[0.0474951  0.63887766 0.94700475 0.18144698 0.3737389 ]


In [8]:
print(matrix)

[[0.28557317 0.02030785 0.26328726 0.80873403 0.34779049]
 [0.08174258 0.30942717 0.25644506 0.07288077 0.50719459]
 [0.84015228 0.05310035 0.69445664 0.87285137 0.46737519]
 [0.87094043 0.36372882 0.92547668 0.98452297 0.5551479 ]
 [0.83545351 0.12014332 0.80490701 0.93261285 0.91138183]]


In [12]:
#random integers belongs to [low, high), total_element  = size
low  = 1
high = 10
size = 3
np.random.randint(low, high, size, dtype = int)

array([5, 8, 9])

In [45]:
print(vec.shape)
print(vec.dtype)
print(vec.data) # return address of 1st elemen
print(vec.strides) # no. of bytes need to skipped to get the next element in the vector (or matrix)
# for 2d array it will return (a, b) where a = no. of need bytes need to skip to get the 
# next row at same column, b = no. of bytes need to skip to get the next element in same row
print(matrix.strides)

(5,)
float64
(8,)
(40, 8)


In [24]:
# 2D arrays & indexing
list_2d = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
np_arr = np.array(list_2d)
print(list_2d)
print(np_arr)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [36]:
print(list_2d[0:3]) # [return row 0,1,2]
print(list_2d[0:3][2]) # ["..."][return 2nd element of output] 
#above will give error for [0:3][3] coz indexing start from 2 => 3rd element
# NOTE : we're NOT getting a part in 2D list, it return entire row
# For a paricular part we need to loop over output
print(np_arr[0:3, 2]) # return all the row values for 2nd column
print(np_arr[0:3][2]) # Working as above list

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
[9, 10, 11, 12]
[ 3  7 11]
[ 9 10 11 12]


In [44]:
# floor divison : a // b
print(10 // 3)
# index of min-element & max-element
print(vec.argmin())
print(np_arr.argmax())
# argmin,.... ONLY work for np-arrays 
#list_2d.argmin() ----> ERROR

3
0
15


In [52]:
# Boolean indexing : extract element i.e; either T or F
arr = np.array([1,12,30,4,5])
print(arr)
print(arr > 5)
# We can even update array using boolean indexing
arr[:3] = 100
print(arr)
#returning index acc. to condition
idx = np.where(arr == 100) # we can use other operators also
print(idx)

[ 1 12 30  4  5]
[False  True  True False False]
[100 100 100   4   5]
(array([0, 1, 2]),)


In [55]:
# Broadcasting of array : used when we want to perform mathematical operation over 2 matrix of diff size
# CONDITION : Either matrix X or Y or both must be row (or column) VECTOR
x = np.array([1,2,3])
z = np.array([[1],[2],[3]])
y = np.array([[9,8,7],[6,5,4],[3,2,1]])
print(x - y)
print(z - y)
print(x - z)
# It will make x of size 3*3 => repeating each row & for z repeating each col 

TypeError: array() takes from 1 to 2 positional arguments but 3 were given